### ISSUE TITLE
Link in ReadMe not working

### ISSUE THREAD

**Issue by ai2ys** [digitaltvguy/NBCU-HDR-SDR-Single-Stream_Workflow_Recommendation#2]
In the top-level ReadMe file the following link results in a 404 error.

"[Click here for short Link to NBCU Single-Stream HDR-SDR Technical Recommendation](https://bit.ly/3KOZS2e)"

**Comment by digitaltvguy** [comment]
Thank you.

I have eliminated the short link.

From: Sylvia Schmitt ***@***.***>
Date: Monday, November 27, 2023 at 9:19 AM
To: digitaltvguy/NBCUniversal-UHD-HDR-SDR-Single-Master-Production-Workflow-Recommendation-LUTs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [digitaltvguy/NBCUniversal-UHD-HDR-SDR-Single-Master-Production-Workflow-Recommendation-LUTs] Link in ReadMe not working (Issue #2)

In the top-level ReadMe file the following link results in a 404 error.

"Click here for short Link to NBCU Single-Stream HDR-SDR Technical Recommendation<https://urldefense.com/v3/__https:/bit.ly/3KOZS2e__;!!PIZeeW5wscynRQ!uyqV0AZtCrYwruHvPtc1WyKnaRwNhLYz9nYfxapjOqavU15cFNloYvYEq8MvmajNSpDu-2QnjDCqvzntsfEaZL1yNQ$>"
